import { router } from '@inertiajs/react'
import { useMemo, useState } from 'react'
import { BarChart3, Bell, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, Copy, Eye, Home, LogOut, MapPin, PackageCheck, Plus, ReceiptText, Settings2, Store, TicketPercent, UserRound, UtensilsCrossed, X } from 'lucide-react'
import type { PaymentStatus, ProviderOrderStatus, ProviderSection } from '@/domain/provider'
import { initialDishes, initialOrders, initialPayments, providerDays, providerProfile, reusableDishes } from '@/mocks/provider'
import styles from './provider-dashboard.module.css'

type Props = { email: string }
type Icon = typeof Home
const nav: Record<ProviderSection, { label: string; icon: Icon }> = {
  home: { label: 'Inicio', icon: Home }, menu: { label: 'Menú', icon: UtensilsCrossed }, orders: { label: 'Pedidos', icon: PackageCheck },
  payments: { label: 'Cobros', icon: CircleDollarSign }, insights: { label: 'Métricas', icon: BarChart3 }, account: { label: 'Cuenta', icon: UserRound },
}
const statusLabel: Record<ProviderOrderStatus, string> = { pending: 'Pendiente', confirmed: 'Confirmado', delivered: 'Entregado', cancelled: 'Cancelado' }

function Header({ eyebrow, title, description, children }: { eyebrow: string; title: string; description?: string; children?: React.ReactNode }) {
  return <header className={styles.header}><div><p>{eyebrow}</p><h1>{title}</h1>{description && <span>{description}</span>}</div>{children}</header>
}
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <article className={styles.stat}><span>{label}</span><strong>{value}</strong><small>{note}</small></article> }

export function ProviderDashboard({ email }: Props) {
  const [section, setSection] = useState<ProviderSection>('home')
  const [day, setDay] = useState(providerDays[0].id)
  const [published, setPublished] = useState<string[]>([])
  const [dishes, setDishes] = useState(initialDishes)
  const [orders, setOrders] = useState(initialOrders)
  const [payments, setPayments] = useState(initialPayments)
  const [orderFilter, setOrderFilter] = useState<'all' | ProviderOrderStatus>('all')
  const [paymentFilter, setPaymentFilter] = useState<'all' | PaymentStatus>('all')
  const [selectedOrder, setSelectedOrder] = useState<string | null>(null)
  const [reuseOpen, setReuseOpen] = useState(false)
  const [notifications, setNotifications] = useState(true)
  const [closingHours, setClosingHours] = useState(1)
  const [toast, setToast] = useState('')
  const currentDay = providerDays.find(item => item.id === day) ?? providerDays[0]
  const visibleOrders = useMemo(() => orders.filter(order => orderFilter === 'all' || order.status === orderFilter), [orders, orderFilter])
  const visiblePayments = useMemo(() => payments.filter(payment => paymentFilter === 'all' || payment.status === paymentFilter), [payments, paymentFilter])
  const detail = orders.find(order => order.id === selectedOrder)
  const navigate = (next: ProviderSection) => { setSection(next); setSelectedOrder(null); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const announce = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2500) }
  const updateOrder = (id: string, status: ProviderOrderStatus) => { setOrders(current => current.map(order => order.id === id ? { ...order, status, cancellationNotice: false } : order)); announce(status === 'confirmed' ? 'Pedido confirmado' : status === 'delivered' ? 'Pedido entregado' : 'Pedido cancelado') }

  const home = <>
    <Header eyebrow="Lunes, 26 de mayo" title={`Hola, ${providerProfile.owner.split(' ')[0]} 👋`}><button className={styles.iconButton} onClick={() => navigate('account')} aria-label="Configuración"><Settings2 /></button></Header>
    {!published.includes(providerDays[0].id) && <button className={styles.alert} onClick={() => navigate('menu')}><Bell /><span><strong>Tu menú de hoy todavía no está publicado</strong><small>Publicalo ahora para no perder pedidos.</small></span><ChevronRight /></button>}
    {orders.some(order => order.cancellationNotice) && <button className={`${styles.alert} ${styles.cancelAlert}`} onClick={() => { setOrderFilter('cancelled'); navigate('orders') }}><Bell /><span><strong>Un pedido confirmado fue cancelado</strong><small>Revisá PED-1046 y ajustá tu preparación.</small></span><ChevronRight /></button>}
    <section className={styles.stats}><Stat label="Pedidos de hoy" value="7" note="2 por confirmar" /><Stat label="Platos a preparar" value="7" note="Wok es el más pedido" /><Stat label="Cierre de pedidos" value="11:30" note={`${closingHours} h antes`} /><Stat label="Cobros pendientes" value="$1.540" note="2 comprobantes" /></section>
    <div className={styles.columns}><section className={styles.surface}><Title eyebrow="Producción" title="Pedidos por plato" action="Ver todos" onAction={() => navigate('orders')} />{[['Wok de verduras + arroz', 3], ['Sorrentinos artesanales', 2], ['Pollo al curry', 2]].map(([name, count]) => <div className={styles.row} key={name}><span>{name}</span><strong>{count}</strong></div>)}</section><section className={styles.surface}><Title eyebrow="Cuenta del día" title="Resumen de cobros" /><div className={styles.money}><span>Total vendido</span><strong>$2.240</strong></div><div className={styles.row}><span>Pagos de empleados</span><strong>$1.120</strong></div><div className={styles.row}><span>Subsidio GoGrow</span><strong>$1.120</strong></div><button className={styles.primary} onClick={() => navigate('payments')}>Revisar cobros</button></section></div>
  </>

  const menu = <>
    <Header eyebrow="Organización de menús" title="Menú" description="Publicá tu oferta para hoy o prepará los próximos días."><button className={styles.primary} onClick={() => announce('Nuevo plato listo para completar')}><Plus /> Nuevo plato</button></Header>
    <div className={styles.days}>{providerDays.map(item => <button key={item.id} data-selected={day === item.id} onClick={() => setDay(item.id)}><span>{item.day}</span><strong>{item.date}</strong>{published.includes(item.id) && <small>Publicado</small>}</button>)}</div>
    <section className={styles.toolbar}><div><CalendarDays /><span><strong>{currentDay.full}</strong><small>{published.includes(day) ? 'Menú publicado' : 'Borrador · todavía no visible'}</small></span></div><div><button className={styles.secondary} onClick={() => setReuseOpen(value => !value)}><Copy /> Reutilizar</button><button className={styles.primary} onClick={() => { setPublished(current => current.includes(day) ? current : [...current, day]); announce(`Menú del ${currentDay.day} publicado`) }}><Check /> Publicar menú</button></div></section>
    {reuseOpen && <section className={styles.reuse}><Title eyebrow="Tu biblioteca" title="Reutilizar un plato anterior" action="Cerrar" onAction={() => setReuseOpen(false)} />{reusableDishes.map(dish => <button key={dish.id} onClick={() => { setDishes(current => current.some(item => item.name === dish.name) ? current : [...current, { ...dish, id: Date.now() }]); setReuseOpen(false); announce(`${dish.name} agregado`) }}><span><strong>{dish.name}</strong><small>{dish.description}</small></span><Plus /></button>)}</section>}
    <div className={styles.dishes}>{dishes.map(dish => <article className={styles.dish} key={dish.id} data-disabled={!dish.available}><span className={styles.food}><UtensilsCrossed /></span><div><span className={styles.state}>{dish.available ? 'Disponible' : 'No disponible'}</span><h2>{dish.name}</h2><p>{dish.description}</p><strong>${dish.price}</strong></div><button className={styles.toggleText} data-enabled={dish.available} onClick={() => setDishes(current => current.map(item => item.id === dish.id ? { ...item, available: !item.available } : item))} role="switch" aria-checked={dish.available}><i />{dish.available ? 'Disponible' : 'Agotado'}</button></article>)}</div>
    <section className={styles.rule}><Clock3 /><div><h2>Regla para recibir pedidos</h2><p>Los empleados deben ordenar al menos <strong>{closingHours} hora{closingHours > 1 ? 's' : ''}</strong> antes.</p></div><select value={closingHours} onChange={event => setClosingHours(Number(event.target.value))} aria-label="Anticipación mínima"><option value={1}>1 hora antes</option><option value={2}>2 horas antes</option><option value={3}>3 horas antes</option></select></section>
  </>

  const ordersView = <><Header eyebrow="Operación diaria" title="Pedidos" description="Confirmá pedidos y organizá la preparación del día." /><Filters values={['all', 'pending', 'confirmed', 'delivered']} selected={orderFilter} labels={{ all: 'Todos', pending: 'Pendientes', confirmed: 'Confirmados', delivered: 'Entregados' }} onChange={value => setOrderFilter(value as typeof orderFilter)} /><div className={styles.orderLayout}><div className={styles.orderList}>{visibleOrders.map(order => <button className={styles.order} data-selected={selectedOrder === order.id} key={order.id} onClick={() => setSelectedOrder(order.id)}><div><span className={styles.avatar}>{order.employeeInitials}</span><span><strong>{order.employee}</strong><small>{order.id} · {order.deliveryTime}</small></span><em data-status={order.status}>{statusLabel[order.status]}</em></div><h2>{order.dish}</h2><p>{order.specifications}</p><footer><span><MapPin />{order.address}</span><strong>${order.amount}</strong></footer></button>)}</div>{detail ? <aside className={styles.detail}><button className={styles.close} onClick={() => setSelectedOrder(null)}><X /> Cerrar</button><p>Detalle del pedido</p><h2>{detail.id}</h2><div className={styles.person}><span className={styles.avatar}>{detail.employeeInitials}</span><span><small>Empleado</small><strong>{detail.employee}</strong></span></div><Info label="Plato" main={detail.dish} detail={detail.specifications} /><Info label="Entrega" main={detail.deliveryTime} detail={detail.address} />{detail.status === 'pending' && <div className={styles.actions}><button className={styles.danger} onClick={() => updateOrder(detail.id, 'cancelled')}>Cancelar</button><button className={styles.primary} onClick={() => updateOrder(detail.id, 'confirmed')}>Confirmar</button></div>}{detail.status === 'confirmed' && <button className={styles.primary} onClick={() => updateOrder(detail.id, 'delivered')}>Marcar como entregado</button>}</aside> : <aside className={styles.empty}><Eye /><p>Seleccioná un pedido para ver toda la información.</p></aside>}</div></>

  const paymentView = <><Header eyebrow="Organización de pagos" title="Cobros" description="Revisá comprobantes y mantené al día las cuentas." /><section className={styles.paymentSummary}><Stat label="Por confirmar" value="$1.540" note="2 comprobantes" /><Stat label="Confirmados en mayo" value="$4.820" note="8 pagos" /><Stat label="Subsidio GoGrow" value="$6.360" note="Liquidación: 5 jun" /></section><Filters values={['all', 'pending', 'confirmed']} selected={paymentFilter} labels={{ all: 'Todos', pending: 'Pendientes', confirmed: 'Confirmados' }} onChange={value => setPaymentFilter(value as typeof paymentFilter)} /><div className={styles.paymentList}>{visiblePayments.map(payment => <article className={styles.payment} key={payment.id}><span className={styles.receipt}><ReceiptText /></span><div><small>{payment.period} · {payment.date}</small><h2>{payment.employee}</h2><button onClick={() => announce(`Vista previa de ${payment.receipt}`)}><Eye /> Ver comprobante</button></div><strong>${payment.amount}</strong><em data-status={payment.status}>{payment.status === 'pending' ? 'Pendiente' : 'Confirmado'}</em>{payment.status === 'pending' && <button className={styles.primary} onClick={() => { setPayments(current => current.map(item => item.id === payment.id ? { ...item, status: 'confirmed' } : item)); announce('Pago confirmado') }}><Check /> Confirmar pago</button>}</article>)}</div></>

  const insights = <><Header eyebrow="Últimos 30 días" title="Métricas" description="Una vista rápida del rendimiento de tu propuesta." /><section className={styles.stats}><Stat label="Pedidos" value="84" note="+12% vs. abril" /><Stat label="Platos vendidos" value="91" note="4,3 por día" /><Stat label="Facturación" value="$28.420" note="Incluye subsidios" /><Stat label="Ticket promedio" value="$338" note="+4% vs. abril" /></section><div className={styles.columns}><section className={styles.surface}><Title eyebrow="Preferencias" title="Platos más pedidos" />{[['Wok de verduras', '32 pedidos'], ['Sorrentinos', '25 pedidos'], ['Pollo al curry', '18 pedidos']].map(([name, count], index) => <div className={styles.rank} key={name}><span>{index + 1}</span><strong>{name}</strong><em>{count}</em></div>)}</section><section className={styles.surface}><Title eyebrow="Tendencia" title="Pedidos por semana" /><div className={styles.chart}>{[42, 65, 54, 86].map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /><small>S{index + 1}</small></div>)}</div></section></div></>

  const account = <><Header eyebrow="Preferencias" title="Mi cuenta" description="Administrá tus datos y notificaciones." /><div className={styles.account}><div><section className={styles.profile}><span className={styles.bigAvatar}>{providerProfile.initials}</span><div><h2>{providerProfile.name}</h2><p>{providerProfile.owner}</p><small>{email}</small></div></section><section className={styles.surface}><div className={styles.setting}><Bell /><span><strong>Notificaciones por WhatsApp</strong><small>Menús, pedidos y cancelaciones.</small></span><button className={styles.switch} role="switch" aria-checked={notifications} data-enabled={notifications} onClick={() => setNotifications(value => !value)}><i /></button></div></section></div><aside><section className={styles.coupon}><TicketPercent /><span><small>Cupones disponibles</small><strong>{providerProfile.coupons}</strong><p>Aplicables a próximas comisiones.</p></span></section><section className={styles.surface}><button className={styles.accountLink}><UserRound /> Datos personales <ChevronRight /></button><button className={styles.accountLink} onClick={() => router.delete('/logout')}><LogOut /> Cerrar sesión <ChevronRight /></button></section></aside></div></>

  const views: Record<ProviderSection, React.ReactNode> = { home, menu, orders: ordersView, payments: paymentView, insights, account }
  return <div className={styles.page}><aside className={styles.sidebar}><div className={styles.brand}><span><Store /></span><strong>GoGrow</strong><small>Proveedor</small></div><nav>{(Object.entries(nav) as Array<[ProviderSection, { label: string; icon: Icon }]>).map(([key, item]) => <button key={key} data-active={section === key} onClick={() => navigate(key)}><item.icon /><span>{item.label}</span></button>)}</nav><div className={styles.sidebarUser}><span className={styles.avatar}>{providerProfile.initials}</span><div><strong>{providerProfile.name}</strong><small>{email}</small></div></div></aside><main className={styles.workspace}>{views[section]}</main><nav className={styles.mobileNav}>{(['home', 'menu', 'orders', 'payments', 'account'] as ProviderSection[]).map(key => { const item = nav[key]; return <button key={key} data-active={section === key} onClick={() => navigate(key)}><item.icon /><span>{item.label}</span></button> })}</nav>{toast && <div className={styles.toast} role="status"><Check />{toast}</div>}</div>
}

function Title({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action?: string; onAction?: () => void }) { return <div className={styles.title}><div><p>{eyebrow}</p><h2>{title}</h2></div>{action && <button onClick={onAction}>{action}</button>}</div> }
function Filters({ values, selected, labels, onChange }: { values: string[]; selected: string; labels: Record<string, string>; onChange: (value: string) => void }) { return <div className={styles.filters}>{values.map(value => <button key={value} data-selected={selected === value} onClick={() => onChange(value)}>{labels[value]}</button>)}</div> }
function Info({ label, main, detail }: { label: string; main: string; detail: string }) { return <div className={styles.info}><small>{label}</small><strong>{main}</strong><span>{detail}</span></div> }
